services:
  app:
    image: node:24-alpine
    container_name: weather.app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "9999:9999"
    command: sh -c "npm install && npm run dev"
    # command: tail -f /dev/null

networks:
  default:
    name: weather.app.network